# sudo docker build --no-cache --tag=pcap_replayer:18.04 .
# sudo docker run -v /home/sulfred/Documents/SoftwareDev/github/SulfredLee/PcapReplayer:/home/sulfred/Documents/SoftwareDev/github/SulfredLee/PcapReplayer -it pcap_replayer:18.04
# This is a comment
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y build-essential cmake ninja-build libboost-all-dev libpcap-dev qt5-default # qtcreator qt5-doc qt5-doc-html qtbase5-dec-html qtbase5-examples
RUN apt-get update
# ADD install.sh ./install.sh
# RUN ./install.sh
